package todo

const ERROR_TODO = 0x8000

const ERROR_NOIMPLEMENTS = ERROR_TODO + 1

const ERROR_TODO_NOT_FOUND_ID = ERROR_TODO + 2

const ERROR_TODO_NOT_FOUND = ERROR_TODO + 3

const ERROR_TODO_PATH = ERROR_TODO + 4

const ERROR_TODO_NOT_FOUND_UID = ERROR_TODO + 5

const ERROR_TODO_USER_NOT_FOUND = ERROR_TODO + 6
